### ISSUE TITLE
TODO before v1

### ISSUE THREAD

**Issue by slayernominee** [slayernominee/cord#1]
- [ ] middleware api block without login
- [ ] login
- [ ] channel fetch
- [ ] server fetch
- [ ] member fetch
- [ ] messages fetch
- [ ] user info fetch
- [ ] send message
- [ ] ... for the elements until they are loaded and not the old elements

**Comment by slayernominee** [comment]
- [ ] messages scrolled down
